project:
  type: book
  output-dir: docs

book:
  title: "International Trade and International Finance"
  author: "Moinul Islam"
  date: "12/1/2023"
  
  chapters:
    - index.qmd
    - lecture_1.qmd
    - lecture_2.qmd
    - lecture_3.qmd
    - lecture_4.qmd
    - lecture_5.qmd
    - lecture_6.qmd
    - lecture_7.qmd
    - lecture_8.qmd
    #- lecture_9.qmd
    #- lecture_10.qmd
    #- lecture_11.qmd
    #- lecture_12.qmd
    #- lecture_13.qmd
    #- lecture_14.qmd
    #- lecture_15.qmd
    - assignment_1.qmd
    - assignment_2.qmd
    - assignment_3.qmd
    - assignment_4.qmd
    - assignment_5.qmd
    - assignment_6.qmd
    - assignment_7.qmd
    - assignment_8.qmd
    #- assignment_9.qmd
    #- assignment_10.qmd
    #- assignment_11.qmd
    #- assignment_12.qmd
    #- assignment_13.qmd
    #- assignment_14.qmd
    #- assignment_15.qmd
    #- final.qmd
    - references.qmd

bibliography: international_trade_finance.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual